Addbio
dbsalazarr/portafolio-personal pull request #4
Opened 2022-02-11 00:29 UTC by dbsalazarr

Se agrego contenido emcional a la biografia

2022-02-11 00:31 UTC, bremdows requested changes
Por favor agrega una linea más en el postblog.html

2022-02-11 00:33 UTC, bremdows reviewed
Gracias

2022-02-11 00:34 UTC, bremdows approved these changes
Gracias por agregar la linea, aprovado.

2022-02-11 00:34 UTC, merged

2022-02-12 03:12 UTC, dbsalazarr commented
Se escribe aprobado mi rey :V